name: "About this PR"

on:
  pull_request:
    branches: [ "master" ]

jobs:
  PR Context:
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"