name: "namingChecker"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  VarFuncName:
    name: namingChecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan variables and functions
        run: |
          git diff --unified=0 HEAD^ | grep -oP '\b((?!new\s*\()[a-z]\w*(?=\())' && exit 1|| echo "No functions starting with lowercase found"
